package xiaobai2;

import java.util.Arrays;

public class lab1 {

public static void main(String[] args) {
    int[] array1 = new int[3];
    System.out.print("The 3 random integer generated by Math.random():");
    for(int i = 0;i<array1.length;i++)
    {
    	array1[i] = (int)(Math.random()*(89)+10);
    	System.out.print(" ");
    	System.out.printf("%3d",array1[i]);
    }
	   Arrays.sort(array1);
	   System.out.print("\n");
	   System.out.println("The max value:"+array1[2]);
	   System.out.println("The min value:"+array1[0]);
	
	}

}
